### ISSUE TITLE
Errors on initial db migration

### ISSUE THREAD

**Issue by nroach** [tigrish/redmine_s3#10]
The following occurs on Heroku Bamboo when I run the initial db migration.  The same error does not occur on Amazon AWS with a Bitnami stack.

*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!

/app/vendor/plugins/redmine_s3/lib/aws/core/client.rb:257:in `return_or_raise'
/app/vendor/plugins/redmine_s3/lib/aws/core/client.rb:316:in`client_request'
(eval):3:in `get_bucket_versioning'
/app/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:100:in`versioning_state'
/app/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:88:in `versioning_enabled?'
/app/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:145:in`exists?'
/app/vendor/plugins/redmine_s3/lib/redmine_s3/connection.rb:43:in `create_bucket'
/app/vendor/plugins/redmine_s3/init.rb:17:in`block in <top (required)>'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:182:in `call'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:182:in`evaluate_method'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:166:in `call'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in`block in run'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in `each'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in`run'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:276:in `run_callbacks'
/app/.bundle/gems/ruby/1.9.1/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:51:in`run_prepare_callbacks'
/app/.bundle/gems/ruby/1.9.1/gems/rails-2.3.14/lib/initializer.rb:631:in `prepare_dispatcher'
/app/.bundle/gems/ruby/1.9.1/gems/rails-2.3.14/lib/initializer.rb:185:in`process'
/app/.bundle/gems/ruby/1.9.1/gems/rails-2.3.14/lib/initializer.rb:113:in `run'
/app/config/environment.rb:42:in`<top (required)>'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in`block in require'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:547:in `new_constants_in'
/app/.bundle/gems/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in`require'
/app/.bundle/gems/ruby/1.9.1/gems/rails-2.3.14/lib/tasks/misc.rake:4:in `block in <top (required)>'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/usr/ruby1.9.2/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`block in invoke_with_call_chain'
/usr/ruby1.9.2/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/app/.bundle/gems/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/app/.bundle/gems/ruby/1.9.1/bin/rake:19:in`load'
/app/.bundle/gems/ruby/1.9.1/bin/rake:19:in `<main>'
Tasks: TOP => db:migrate => environment

**Comment by nroach** [comment]
It turns out this is related to running on Chiliproject 3.0.0.  The plugin is compatible with 2.7.0, but fails on v3.  I suspect this is related to the attachment handling changes made in chiliproject.
