### ISSUE TITLE
Move file if use external DB

### ISSUE THREAD

**Issue by cyberflow** [tigrish/redmine_s3#12]
If i run # rake redmine_s3:files_to_s3
(in /var/www/redmine)
rake aborted!
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

I use external MySQL database. What I can change in script for move files to S3?

Thanks.

**Comment by cyberflow** [comment]
# rake --trace redmine_s3:files_to_s3

(in /var/www/redmine-1.2)
*\* Invoke redmine_s3:files_to_s3 (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/mysql_adapter.rb:620:in`connect'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/mysql_adapter.rb:203:in `initialize'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/mysql_adapter.rb:75:in`new'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/mysql_adapter.rb:75:in `mysql_connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:223:in`send'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:223:in `new_connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:245:in`checkout_new_connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:188:in `checkout'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in`loop'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in `checkout'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:183:in `checkout'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:98:in`connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:326:in `retrieve_connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_specification.rb:123:in`retrieve_connection'
/var/lib/gems/1.8/gems/activerecord-2.3.11/lib/active_record/connection_adapters/abstract/connection_specification.rb:115:in `connection'
/var/www/redmine-1.2/vendor/plugins/awesome_nested_set/lib/awesome_nested_set.rb:218:in`quoted_left_column_name'
/var/www/redmine-1.2/vendor/plugins/awesome_nested_set/lib/awesome_nested_set.rb:93:in `acts_as_nested_set'
/var/www/redmine-1.2/app/models/issue.rb:37
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in`load_without_new_constant_marking'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in`require_or_load'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:451:in `load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in`const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:118:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:122:in `const_missing'
/var/www/redmine-1.2/app/models/project.rb:40
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in`load_without_new_constant_marking'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in`require_or_load'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:451:in `load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in`const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:118:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:122:in `const_missing'
/var/www/redmine-1.2/app/models/attachment.rb:36
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in`load_without_new_constant_marking'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in`new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in `load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in`require_or_load'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:451:in `load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in`const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:118:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:463:in`load_missing_constant'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:106:in `const_missing'
/var/www/redmine-1.2/vendor/plugins/acts_as_attachable/lib/acts_as_attachable.rb:33:in`acts_as_attachable'
/var/www/redmine-1.2/app/models/wiki_page.rb:24
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in `load_without_new_constant_marking'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:406:in`load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:405:in`load_file'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:285:in `require_or_load'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:250:in`depend_on'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:162:in `require_dependency'
/var/www/redmine-1.2/vendor/plugins/haru_iida-redmine_wiki_extensions-9191b17f6192/lib/wiki_extensions_wiki_page_patch.rb:17
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/var/www/redmine-1.2/vendor/plugins/haru_iida-redmine_wiki_extensions-9191b17f6192/init.rb:26:in `evaluate_init_rb'
/var/www/redmine-1.2/vendor/plugins/haru_iida-redmine_wiki_extensions-9191b17f6192/init.rb:24:in`foreach'
/var/www/redmine-1.2/vendor/plugins/haru_iida-redmine_wiki_extensions-9191b17f6192/init.rb:24:in `evaluate_init_rb'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin.rb:158:in`evaluate_init_rb'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin.rb:154:in`evaluate_init_rb'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin.rb:48:in `load'
/var/www/redmine-1.2/config/../vendor/plugins/engines/lib/engines/plugin.rb:44:in`load'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin/loader.rb:38:in `load_plugins'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin/loader.rb:37:in`each'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/rails/plugin/loader.rb:37:in `load_plugins'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:369:in`load_plugins'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:165:in `process'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in`send'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
/var/www/redmine-1.2/config/environment.rb:20
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in`require'
/var/lib/gems/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in`execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in`execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in`invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in`invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in`invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
