### ISSUE TITLE
Error on Uploads | (eval):3:in `head_object'

### ISSUE THREAD

**Issue by bishopandco** [tigrish/redmine_s3#7]
ChiliProject 2.4 Ruby 1.9.2

<pre>
Processing IssuesController#update (for xxx.xxx.xxx.xxx at 2011-11-21 22:24:33) [PUT]
  Parameters: {"_method"=>"put", "authenticity_token"=>"zvCqkCNFRNfou5O0WXubDwUPfRMBF3EpjMcnb5a9Lc8=", "issue"=>{"tracker_id"=>"1", "subject"=>"favicon", "parent_issue_id"=>"", "description"=>"xxxxxxxxx", "status_id"=>"1", "priority_id"=>"4", "assigned_to_id"=>"72", "fixed_version_id"=>"", "start_date"=>"2011-11-11", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "custom_field_values"=>{"2"=>"No"}, "lock_version"=>"4"}, "time_entry"=>{"hours"=>"", "activity_id"=>"", "comments"=>""}, "notes"=>"", "attachments"=>{"1"=>{"file"=>#<File:/tmp/RackMultipart20111121-23068-p5c8ur>, "description"=>""}}, "send_notification"=>"1", "commit"=>"Submit", "controller"=>"issues", "action"=>"update", "id"=>"2029"}

AWS::Errors::Base (AWS::Errors::Base):
  (eval):3:in `head_object'
  app/models/attachment.rb:160:in `block in attach_files'
  app/models/attachment.rb:157:in `each_value'
  app/models/attachment.rb:157:in `attach_files'
  app/models/issue.rb:581:in `block in save_issue_with_child_records'
  app/models/issue.rb:569:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:158:in `update'
  <internal:prelude>:10:in `synchronize'
  passenger (3.0.1) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.1) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.1) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.1) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.1) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
  passenger (3.0.1) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.1) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.1) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.1) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.1) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.1) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.1) lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
  passenger (3.0.1) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.1) lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
  passenger (3.0.1) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  passenger (3.0.1) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.1) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.1) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.1) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.1) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.1) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.1) helper-scripts/passenger-spawn-server:99:in `<main>'

Rendering /home/deploy/releases/20111121032816/public/500.html (500 Internal Server Error)
</pre>

<pre>

gem list

*** LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.3, 2.3.14, 2.3.5, 2.3.4)
actionpack (3.0.3, 2.3.14, 2.3.5, 2.3.4)
activemodel (3.0.3)
activerecord (3.0.3, 2.3.14, 2.3.5, 2.3.4)
activeresource (3.0.3, 2.3.14, 2.3.5, 2.3.4)
activesupport (3.0.3, 2.3.14, 2.3.5, 2.3.4)
acts-as-taggable-on (2.0.6)
annotate (2.4.0)
archive-tar-minitar (0.5.2)
arel (2.0.7, 2.0.6, 2.0.4)
authlogic (2.1.3)
awesome_nested_set (1.4.3)
bcrypt-ruby (2.1.4, 2.1.3, 2.1.2)
builder (2.1.2)
bundler (1.0.7)
cable_menu (0.0.4)
cancan (1.1.1)
capistrano (2.5.19)
capistrano-ext (1.2.1)
cinch (1.1.3)
coderay (0.9.8)
colored (1.2)
columnize (0.3.4)
daemon_controller (0.2.5)
devise (1.1.5)
devise_invitable (0.3.5)
edavis10-object_daddy (0.4.3)
erubis (2.6.6)
fastthread (1.0.7)
file-tail (1.0.5)
formtastic (1.2.3, 1.2.2, 1.2.1)
geokit (1.5.0)
geokit-rails3 (0.1.2)
git (1.2.5)
git_remote_branch (0.3.0)
google_image_api (0.0.1)
highline (1.6.1)
hirb (0.3.5)
i18n (0.5.0, 0.4.2)
inifile (0.4.1, 0.3.0)
jeweler (1.5.2)
jquery-rails (0.2.7, 0.2.6, 0.2.5)
json (1.6.1)
linecache19 (0.5.12)
lockfile (1.4.3)
mail (2.2.15, 2.2.12, 2.2.11, 2.2.10)
metaclass (0.0.1)
mime-types (1.16)
mocha (0.10.0)
mysql (2.8.1)
mysql2 (0.2.17, 0.2.6)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.1.4, 2.1.0, 2.0.23)
net-ssh-gateway (1.0.1)
nokogiri (1.5.0, 1.4.4)
paperclip (2.3.8, 2.3.6, 2.3.5, 2.3.1.1)
passenger (3.0.5, 3.0.1, 3.0.0)
polyglot (0.3.1)
rack (1.2.1, 1.1.2, 1.0.1)
rack-mount (0.6.13)
rack-test (0.5.7, 0.5.6)
rails (3.0.3, 2.3.14, 2.3.5, 2.3.4)
railties (3.0.3)
rake (0.9.2.2, 0.8.7)
rdoc (3.11)
riddle (1.2.1)
ruby-debug-base19 (0.11.25)
ruby-debug19 (0.11.6)
ruby-ole (1.2.11.1)
ruby-openid (2.1.8)
ruby_core_source (0.1.5)
rubytree (0.5.3)
sanitize (1.2.1)
seedbed (1.0.1, 0.4.0)
shoulda (2.10.3)
simple-navigation (3.1.0, 3.0.2)
spreadsheet (0.6.5.0)
spruz (0.2.2)
sqlite3 (1.3.3)
sqlite3-ruby (1.3.3)
thinking-sphinx (2.0.0)
thor (0.14.6)
treetop (1.4.9)
tzinfo (0.3.24, 0.3.23)
warden (1.0.3, 1.0.2)
will_paginate (3.0.pre2)
wirble (0.1.3)
xmpp4r (0.5)
</pre>

<pre>

rvm info

ruby-1.9.2-p0:

  system:
    uname:       "Linux xxx.xxx.com 2.6.18-194.26.1.el5 #1 SMP Tue Nov 9 12:54:20 EST 2010 x86_64 x86_64 x86_64 GNU/Linux"
    bash:        "/bin/bash => GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.1.3 by Wayne E. Seguin (wayneeseguin@gmail.com) [http://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p0"
    date:         "2010-08-18"
    platform:     "x86_64-linux"
    patchlevel:   "2010-08-18 revision 29036"
    full_version: "ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-1.9.2-p0"
    ruby:         "/usr/local/rvm/rubies/ruby-1.9.2-p0"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-1.9.2-p0/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-1.9.2-p0/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-1.9.2-p0/bin/gem"
    rake:         "/usr/local/rvm/gems/ruby-1.9.2-p0/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-1.9.2-p0/bin:/usr/local/rvm/gems/ruby-1.9.2-p0@global/bin:/usr/local/rvm/rubies/ruby-1.9.2-p0/bin:/usr/local/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/rvm/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-1.9.2-p0"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-1.9.2-p0:/usr/local/rvm/gems/ruby-1.9.2-p0@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-1.9.2-p0"
    IRBRC:        "/usr/local/rvm/rubies/ruby-1.9.2-p0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
</pre>

**Comment by bishopandco** [comment]
I just realized it's totally unfair to count this is as a bug as ChiliProject changed versions into Journals.
