### ISSUE TITLE
get_bucket_versioning error

### ISSUE THREAD

**Issue by jschoolcraft** [tigrish/redmine_s3#8]
I'm using this with CP on Heroku.

The gist of the error is here: https://gist.github.com/286f26ff43fc37dd7488 but I'll inline it here as well:

```
=> Booting WEBrick
=> Rails 2.3.14 application starting on http://0.0.0.0:3000
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/rails/gem_dependency.rb:21.
/Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/aws/core/client.rb:257:in `return_or_raise': AWS::Errors::Base
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/aws/core/client.rb:316:in `client_request'
    from (eval):3:in `get_bucket_versioning'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:100:in `versioning_state'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:88:in `versioned?'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/aws/s3/bucket.rb:145:in `exists?'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/lib/redmine_s3/connection.rb:43:in `create_bucket'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/vendor/plugins/redmine_s3/rails/../init.rb:17
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:182:in `call'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:182:in `evaluate_method'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:166:in `call'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in `run'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in `each'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in `send'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:90:in `run'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:276:in `run_callbacks'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:51:in `send'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:51:in `run_prepare_callbacks'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/initializer.rb:631:in `prepare_dispatcher'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/initializer.rb:185:in `process'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/initializer.rb:113:in `send'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/initializer.rb:113:in `run'
    from /Volumes/Master/jschoolcraft/code/cp-heroku/config/environment.rb:39
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:547:in `new_constants_in'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
    from /Volumes/Master/jschoolcraft/.rvm/gems/ruby-1.8.7-p352/gems/rails-2.3.14/lib/commands/server.rb:84
    from script/server:4:in `require'
    from script/server:4
```

my config/s3.yml looks like:

```

production:
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %> 
  endpoint:
  secure: false
  private:
  expires: 

development:
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %> 
  endpoint:
  secure: false
  private:
  expires: 
```

I've tried it with and without the bucket existing, credentials are correct.

**Comment by nroach** [comment]
I think I'm seeing the same root cause in a slightly different context in Issue #10.
